# Generated by Django 5.0.7 on 2025-07-31 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='计数记录',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('触发时间', models.DateTimeField(default=django.utils.timezone.now, verbose_name='触发时间')),
            ],
            options={
                'verbose_name': '计数记录',
                'verbose_name_plural': '计数记录',
                'ordering': ['-触发时间'],
            },
        ),
    ]
