# Generated by Django 5.0.7 on 2025-01-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=64, verbose_name='项目名称')),
                ('code', models.CharField(help_text='项目编码', max_length=32, verbose_name='项目编码')),
                ('status', models.CharField(help_text='项目状态', max_length=64, verbose_name='项目状态')),
            ],
        ),
    ]
